console.log("hello world!")
console.log("hello china!")
console.log("hello russia")
console.log("我是jun子分支")
console.log("---------------------")
console.log("我是主分支")
console.log("---------------------")